### ISSUE TITLE
AX1800 无法打开http://clash.razord.top 

### ISSUE THREAD

**Issue by Kandom** [juewuy/clash-for-Miwifi#2]
启用后可以通过 http://clash.razord.top （IP为网关IP，端口为9999）管理clash内置规则

可以打开http://192.168.31.1:9999 有JSON 返回
无法打开http://clash.razord.top

AX1800，V2Ray，ws + tls 模式

**Comment by juewuy** [comment]
更新一下配置文件（新版配置文件将面板地址强制设置为直连）或者ssh里先关闭clash再打开改地址，之后再开启clash。
本质上应该是你代理服务器配置有问题导致clash本身无法代理国外流量。
