### ISSUE TITLE
ax3600  /bin: Read-only file system

### ISSUE THREAD

**Issue by chunge6336** [juewuy/clash-for-Miwifi#4]
root@XiaoQiang:~# chmod 755 /bin
chmod: /bin: Read-only file system
求解，这方法无效。。

**Comment by juewuy** [comment]
暂时先用sh /etc/clash/clashsh 执行脚本，有条件可以加tg群详细了解一下

**Comment by chunge6336** [comment]
好的，感谢大佬

> 暂时先用sh /etc/clash/clashsh 执行脚本，0.2的脚本加入了文件检测需要修改文件内容才能使用，可以先用0.1版的脚本凑合用一下。有条件可以加tg群详细了解一下

**Comment by juewuy** [comment]
试一下 mount -o remount rw /bin 或者mount -o remount rw / ，看看是否有效。另外问一句你的路由器是否是刷过第三方系统？

**Comment by chunge6336** [comment]
> 试一下 mount -o remount rw /bin 或者mount -o remount rw / ，看看是否有效。另外问一句你的路由器是否是刷过第三方系统？

之前试过无效，刷过openwrt，又刷回来了

**Comment by juewuy** [comment]
> > 试一下 mount -o remount rw /bin 或者mount -o remount rw / ，看看是否有效。另外问一句你的路由器是否是刷过第三方系统？
> 
> 之前试过无效，刷过openwrt，又刷回来了

应该是刷机时扩大了可用空间导致的bug 系统没法挂载，下一版我会把脚本里面的判断挪到其他文件里，这样脚本就可以在任意位置运行了

**Comment by syq7970** [comment]
同样遇到这个问题，没有刷过其他系统，mount -o remount rw /也无效。。

**Comment by syq7970** [comment]
> > > 试一下 mount -o remount rw /bin 或者mount -o remount rw / ，看看是否有效。另外问一句你的路由器是否是刷过第三方系统？
> > 
> > 
> > 之前试过无效，刷过openwrt，又刷回来了
> 
> 应该是刷机时扩大了可用空间导致的bug 系统没法挂载，下一版我会把脚本里面的判断挪到其他文件里，这样脚本就可以在任意位置运行了

同样遇到这个问题，没有刷过其他系统，mount -o remount rw /也无效。。
