### ISSUE TITLE
我这个还不支持订阅？更新也在施工，

### ISSUE THREAD

**Issue by Marblog** [juewuy/clash-for-Miwifi#6]
![image](https://user-images.githubusercontent.com/22953256/89042586-baff0480-d379-11ea-8cbb-2ba69b6ac91d.png)
![image](https://user-images.githubusercontent.com/22953256/89042628-d0742e80-d379-11ea-8fd2-876649e6e61e.png)
怎么更新？？我直接替换的文件

**Comment by juewuy** [comment]
重新上传之后执行一下安装命令
