### ISSUE TITLE
AX5无法使用

### ISSUE THREAD

**Issue by GeneKong** [juewuy/clash-for-Miwifi#7]
1. 目前的版本配置文件总是生成在根目录；测试启动会提示：
INFO[0000] Can't find config, create a initial config file
INFO[0000] Can't find MMDB, start download
FATA[0001] Initial configuration directory error: Can't initial MMDB: Can't download MMDB: Get "https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb": x509: certificate signed by unknown authority
2. 将config.yaml拷贝到/etc/clash目录；测试启动会提示：
root@XiaoQiang:/etc/clash# INFO[0000] Can't find config, create a initial config file
> INFO[0000] Can't find MMDB, start download
-ash: INFO[0000]: not found
root@XiaoQiang:/etc/clash# FATA[0001] Initial configuration directory error: Can't initial MMDB: Can't download MMDB: Get "https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmd
b": x509: certificate signed by unknown authority

**Comment by GeneKong** [comment]
root@XiaoQiang:/etc/clash# ./clash -f config.yaml -t -d .
INFO[0000] Start initial compatible provider Ⓜ️ 微软服务
INFO[0000] Start initial compatible provider 📲 电报信息
INFO[0000] Start initial compatible provider 🍎 苹果服务
INFO[0000] Start initial compatible provider 🌍 国外媒体
INFO[0000] Start initial compatible provider 🍃 应用净化
INFO[0000] Start initial compatible provider 🐟 漏网之鱼
INFO[0000] Start initial compatible provider 🛑 全球拦截
INFO[0000] Start initial compatible provider 🎯 全球直连
INFO[0000] Start initial compatible provider 📢 谷歌FCM
INFO[0000] Start initial compatible provider ♻️ 自动选择
INFO[0000] Start initial compatible provider 🚀 节点选择

**Comment by GeneKong** [comment]
clash.sh 里面的cpath为空，貌似没起作用

**Comment by juewuy** [comment]
这个问题会在今天的稍后时间修复
