### ISSUE TITLE
在AX5上面，使用脚本启动后无发正常工作

### ISSUE THREAD

**Issue by GeneKong** [juewuy/clash-for-Miwifi#8]
1. 使用0.8的脚本：
clash服务启动失败！请检查配置文件！
不过在手动执行clash -d . 后可以正常运行。

怀疑clash是deamon线程，无法使用procd启动，我把脚本改成如下可以正常工作：
```
start_service() {
	getconfig
	modifyyaml
    #创建clash后台进程
    $clashdir/clash -d $clashdir> /dev/null &
	#procd_open_instance
	#procd_set_param respawn
	#procd_set_param stderr 1
	#procd_set_param stdout 1
	#procd_set_param command $clashdir/clash -d $clashdir
	#procd_close_instance
	#修改iptables规则使流量进入clash
	stop_redir
	start_tun
	start_redir
	mark_time
}
stop_service() {
	stop_redir
	kill -9 `ps | grep '/etc/clash' | grep -v 'grep' | awk '{print $1}'`
}
```
不过修改后无法使用你的管理脚本停止，手工执行可以。

**Comment by juewuy** [comment]
正常官方系统肯定是可以用procd启动的，能提供下你的设备信息吗？

**Comment by GeneKong** [comment]
我是官方系统，这两天才买的，仅仅开了ssh权限
```
BusyBox v1.25.1 (2020-07-13 12:23:03 UTC) built-in shell (ash)

 -----------------------------------------------------
       Welcome to XiaoQiang!
 -----------------------------------------------------
  $$$$$$\  $$$$$$$\  $$$$$$$$\      $$\      $$\        $$$$$$\  $$\   $$\
 $$  __$$\ $$  __$$\ $$  _____|     $$ |     $$ |      $$  __$$\ $$ | $$  |
 $$ /  $$ |$$ |  $$ |$$ |           $$ |     $$ |      $$ /  $$ |$$ |$$  /
 $$$$$$$$ |$$$$$$$  |$$$$$\         $$ |     $$ |      $$ |  $$ |$$$$$  /
 $$  __$$ |$$  __$$< $$  __|        $$ |     $$ |      $$ |  $$ |$$  $$<
 $$ |  $$ |$$ |  $$ |$$ |           $$ |     $$ |      $$ |  $$ |$$ |\$$\
 $$ |  $$ |$$ |  $$ |$$$$$$$$\       $$$$$$$$$  |       $$$$$$  |$$ | \$$\
 \__|  \__|\__|  \__|\________|      \_________/        \______/ \__|  \__|


-ash: source: line 61: can't open '/etc/mixbox/config/profile'
root@XiaoQiang:~# cd /etc/clash/
root@XiaoQiang:/etc/clash#
root@XiaoQiang:/etc/clash#
root@XiaoQiang:/etc/clash# uname -a
Linux XiaoQiang 4.4.60 #0 SMP PREEMPT Mon Jul 13 12:00:51 2020 armv7l GNU/Linux
```

**Comment by GeneKong** [comment]
![image](https://user-images.githubusercontent.com/1146101/89610777-fe8fcc00-d8ad-11ea-812a-d3e73d7e9f9d.png)

**Comment by GeneKong** [comment]
如果其他人没有反馈这个问题，就当特例吧

**Comment by GeneKong** [comment]
唯一的操作就是装过mibox，不太好使，卸载过

**Comment by juewuy** [comment]
-ash: source: line 61: can't open '/etc/mixbox/config/profile'
怀疑是之前mixbox没卸载干净导致的，可能是占用了procd进程导致进程无法运行其他应用
去init.d下面找找有没有mixbox的相关文件

**Comment by GeneKong** [comment]
这个是profile上面加的一行，我删掉了，我有时间把这个路由器复位之后再试试。
如果有其他人的AX5使用是OK的，那这个问题可能是其它原因导致的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "juewuy"<notifications@github.com&gt;; 
发送时间: 2020年8月7日(星期五) 中午1:37
收件人: "juewuy/clash-for-Miwifi"<clash-for-Miwifi@noreply.github.com&gt;; 
抄送: "以心之名"<gyx_edu@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [juewuy/clash-for-Miwifi] 在AX5上面，使用脚本启动后无发正常工作 (#8)





 
-ash: source: line 61: can't open '/etc/mixbox/config/profile'
 怀疑是之前mixbox没卸载干净导致的，可能是占用了procd进程导致进程无法运行其他应用
 建议去init.d下面找找有没有mixbox的相关文件
 
&mdash;

**Comment by juewuy** [comment]
单独删掉这个肯定是无意义的，主要影响启动的应该是mixbox的守护进程，你可以尝试使用service命令查看是否有mixbox相关的开机启动项，然后使用service mixbox disable来禁止启动。
应该就能解决问题
实在无法解决，重置也是无奈之举，但是至少目前其他用户没有报告此类问题的

**Comment by GeneKong** [comment]
现在路由器要用，恢复出厂设置后的结论抽时间贴上来。

**Comment by GeneKong** [comment]
在重置之后，是可以工作的，这个很奇怪；这个mibox看样子没处理干净。
这个问题可以关闭了。

**Comment by GeneKong** [comment]
还有点差异，这次我用的执行文件是：bin\clash\clash-linux-armv7
而上次用的你的readme里提供的压缩包带的clash程序。
